"""0002 add surname

Revision ID: d713f41ad19f
Revises: 0ddc960cfaf1
Create Date: 2025-11-05 17:43:50.722816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd713f41ad19f'
down_revision = '0ddc960cfaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), nullable=False))
        batch_op.drop_index(batch_op.f('ix_authors_name'))
        batch_op.create_index(batch_op.f('ix_authors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_authors_surname'), ['surname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_surname'))
        batch_op.drop_index(batch_op.f('ix_authors_name'))
        batch_op.create_index(batch_op.f('ix_authors_name'), ['name'], unique=1)
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
